"""empty message

Revision ID: 0ea1ee34606a
Revises: 
Create Date: 2019-02-17 20:03:14.512821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea1ee34606a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod', sa.String(length=80), nullable=True),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('molinete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_cod', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['evento_cod'], ['evento.cod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credencial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.Column('molinete_id', sa.Integer(), nullable=True),
    sa.Column('evento_cod', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['evento_cod'], ['evento.cod'], ),
    sa.ForeignKeyConstraint(['molinete_id'], ['molinete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credencial')
    op.drop_table('molinete')
    op.drop_table('evento')
    # ### end Alembic commands ###
