"""empty message

Revision ID: 50616ed38546
Revises: 
Create Date: 2019-02-17 15:22:31.611339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50616ed38546'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credencial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credencial')
    # ### end Alembic commands ###
