"""empty message

Revision ID: 63e58a60d2e7
Revises: 0ea1ee34606a
Create Date: 2019-02-19 01:56:16.410207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e58a60d2e7'
down_revision = '0ea1ee34606a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lectura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('credencial_id', sa.Integer(), nullable=True),
    sa.Column('molinete_id', sa.Integer(), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credencial_id'], ['credencial.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['molinete_id'], ['molinete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lectura_timestamp'), 'lectura', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lectura_timestamp'), table_name='lectura')
    op.drop_table('lectura')
    # ### end Alembic commands ###
